### ISSUE TITLE
ArgumentError on every POST request

### ISSUE THREAD

**Issue by mvader** [lotus/lotus#196]
Hi,

I've been experiencing an issue with lotus 0.3.0. The same code unmodified works perfectly with lotus 0.2.1.

Whenever I submit a form via POST I get this error:
````
ArgumentError: undefined class/module Lotus::Utils::Escape::
	/usr/local/lib/ruby/gems/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:41:in `load'
	/usr/local/lib/ruby/gems/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:41:in `proceed_as_parent'
	/usr/local/lib/ruby/gems/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:28:in `call!'
	/usr/local/lib/ruby/gems/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.11.1/lib/puma/rack_patch.rb:13:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.11.1/lib/puma/server.rb:507:in `handle_request'
	/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
	/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
	/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```
Here's mi [Gemfile.lock](https://gist.github.com/mvader/0efa6775ddbed8166dcd)

**Comment by jodosha** [comment]
Hello @mvader and thanks for reporting. This seems to be an issue that affects v0.3.0 in general, and not because of the upgrade.

Can you please amend your `Gemfile` and verify it fixes the problem for you?

```ruby
gem 'lotus-controller', github: 'lotus/controller', branch: 'ensure-string-for-redirect'
```

**Comment by mvader** [comment]
@jodosha yes, that fixes the problem. 
Waiting for 0.3.1 then :) :+1:

**Comment by mereghost** [comment]
Hmmm... I have stumbled on that behavior (development only, shotgun enabled) when explicit setting the location header while using a routing helper. 

Just a very contrived example:

```ruby
module Awesome::Controllers::App
  class Create
    def call(params)
      # magic happens
      rainbow = RainbowRepository.create(Rainbow.new)
      self.status = 201
      headers['Location'] = routes.url(:rainbow, id: rainbow.id)
      self.body = ''
    end
  end
end

**Comment by mereghost** [comment]
I may also add that enveloping the `routes` call in a `String.new` as was done to fix the issue at hand, also fixes the problem.

Is that expected behavior or should we find a way to fix it?
