### ISSUE TITLE
New application with default route, errors looking for 'xhtml' template

### ISSUE THREAD

**Issue by thecatwasnot** [lotus/lotus#220]
Lotus app generated with `bundle exec lotus new`, uncomment default route: `get '/', to: 'home#index'`
Results in error:
```
Lotus::View::MissingTemplateError: Can't find template 'home/index' for 'xhtml' format.

/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotus-view-0.4.0/lib/lotus/view/rendering.rb:143:in `template'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotus-view-0.4.0/lib/lotus/view/rendering.rb:117:in `rendered'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotus-view-0.4.0/lib/lotus/view/rendering.rb:131:in `layout'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotus-view-0.4.0/lib/lotus/view/rendering.rb:104:in `render'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotus-view-0.4.0/lib/lotus/view/rendering.rb:236:in `render'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotusrb-0.3.0/lib/lotus/rendering_policy.rb:44:in `_render_action'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotusrb-0.3.0/lib/lotus/rendering_policy.rb:37:in `_render'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotusrb-0.3.0/lib/lotus/rendering_policy.rb:28:in `render'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotusrb-0.3.0/lib/lotus/application.rb:214:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/http_router-0.11.1/lib/http_router.rb:193:in `process_destination_path'
(eval):15:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/http_router-0.11.1/lib/http_router.rb:288:in `raw_call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotus-router-0.3.0/lib/lotus/routing/http_router.rb:112:in `raw_call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/http_router-0.11.1/lib/http_router.rb:142:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotus-router-0.3.0/lib/lotus/router.rb:879:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/lotusrb-0.3.0/lib/lotus/container.rb:20:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/rack-1.6.1/lib/rack/lint.rb:49:in `_call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/rack-1.6.1/lib/rack/lint.rb:37:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
/home/thecatwasnot/.rvm/gems/ruby-2.2.0@testnewapp/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
/home/thecatwasnot/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/thecatwasnot/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/thecatwasnot/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```
Fresh gemset/bundle, gem list:
```
bigdecimal (1.2.6)
bundler (1.7.12)
bundler-unload (1.0.2)
capybara (2.4.4)
dotenv (1.0.2)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
http_router (0.11.1)
io-console (0.4.3)
json (1.8.1)
lotus-controller (0.4.0)
lotus-helpers (0.1.0)
lotus-model (0.3.0)
lotus-router (0.3.0)
lotus-utils (0.4.0)
lotus-validations (0.3.0)
lotus-view (0.4.0)
lotusrb (0.3.0)
mime-types (2.5)
mini_portile (0.6.2)
minitest (5.6.1, 5.4.3)
nokogiri (1.6.6.2)
power_assert (0.2.2)
psych (2.0.8)
rack (1.6.1)
rack-test (0.6.3)
rake (10.4.2)
rdoc (4.2.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sequel (4.22.0)
shotgun (0.9.1)
test-unit (3.0.8)
thor (0.19.1)
tilt (2.0.1)
url_mount (0.2.1)
xpath (2.0.0)
```
Tried on chrome & firefox, same result

**Comment by jodosha** [comment]
@thecatwasnot Hello and thanks for reporting this. Can you please check if this PR fixes your problem as well? https://github.com/lotus/controller/pull/105

Ref https://github.com/lotus/controller/issues/104

**Comment by AlfonsoUceda** [comment]
FYI, with `bundle exec lotus new --lotus-head=true` works ok

**Comment by thecatwasnot** [comment]
@jodosha @AlfonsoUceda Yep, --lotus-head works as expected, thanks :+1:
