### ISSUE TITLE
JRuby-9K: Lotus Server Doesn't Work

### ISSUE THREAD

**Issue by sdogruyol** [lotus/lotus#237]
We use WeBrick as the default server in development and we use Shotgun to reload the app.

Shotgun uses fork to spawn a new child process and then quits the old one. Since fork is not supported on JRuby we get a runtime error when trying to visit the app on browser.

Here's the stacktrace.

```
lotus-sample git:(master) ✗ bundle exec lotus server
uri:classloader:/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
[2015-05-27 11:46:28] INFO  WEBrick 1.3.1
[2015-05-27 11:46:28] INFO  ruby 2.2.2 (2015-05-25) [java]
[2015-05-27 11:46:28] INFO  WEBrick::HTTPServer#start: pid=5205 port=2300
[2015-05-27 11:46:39] ERROR NotImplementedError: fork is not available on this platform
	org/jruby/RubyKernel.java:1728:in `fork'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/shotgun-0.9.1/lib/shotgun/loader.rb:27:in `call!'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/lint.rb:49:in `_call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/lint.rb:37:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
	/Users/serdardogruyol/.rvm/rubies/jruby-head/lib/ruby/stdlib/webrick/httpserver.rb:138:in `service'
	/Users/serdardogruyol/.rvm/rubies/jruby-head/lib/ruby/stdlib/webrick/httpserver.rb:94:in `run'
	/Users/serdardogruyol/.rvm/rubies/jruby-head/lib/ruby/stdlib/webrick/server.rb:294:in `block in start_thread'
[2015-05-27 11:46:39] ERROR NotImplementedError: fork is not available on this platform
	org/jruby/RubyKernel.java:1728:in `fork'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/shotgun-0.9.1/lib/shotgun/loader.rb:27:in `call!'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/lint.rb:49:in `_call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/lint.rb:37:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
	/Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
	/Users/serdardogruyol/.rvm/rubies/jruby-head/lib/ruby/stdlib/webrick/httpserver.rb:138:in `service'
	/Users/serdardogruyol/.rvm/rubies/jruby-head/lib/ruby/stdlib/webrick/httpserver.rb:94:in `run'
	/Users/serdardogruyol/.rvm/rubies/jruby-head/lib/ruby/stdlib/webrick/server.rb:294:in `block in start_thread'
^C[2015-05-27 11:50:19] INFO  going to shutdown ...
[2015-05-27 11:50:19] INFO  WEBrick::HTTPServer#start done.
```

We need to replace either WeBrick or Shotgun with something else on JRuby.

**Comment by Sdogruyol** [comment]
Related PR at https://github.com/lotus/lotus/pull/238 :+1:

**Comment by jodosha** [comment]
@Sdogruyol Can you please test this for me using JRuby?

```shell
brew update && brew install entr
cd path/to/project
find . | entr -r bundle exec lotus server --no-code-reloading
```

Visit a page, edit a source file and visit again, to check if code reloading works. It does locally for me.

**Comment by Sdogruyol** [comment]
@jodosha gonna check now. Btw what is ``entr``?

**Comment by Sdogruyol** [comment]
Unfortunately it's not working on JRuby probably not related to ```entr```

Here's the stacktrace

```
uri:classloader:/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
IOError: closed stream
  gets at org/jruby/RubyIO.java:2202
uri:classloader:/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
JRuby doesn't support code reloading.
JRuby doesn't support code reloading.
/Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotus-utils-0.4.3/lib/lotus/utils/path_prefix.rb:140: warning: private attribute?
/Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotusrb-0.3.2/lib/lotus/loader.rb:34: warning: private attribute?
/Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotusrb-0.3.2/lib/lotus/loader.rb:34: warning: private attribute?
RuntimeError: Cannot instantiate adapter of Lotus::Model::Adapters::SqlAdapter (LoadError: no such file to load -- pg)
                instantiate_adapter at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotus-model-0.3.2/lib/lotus/model/config/adapter.rb:101
                              build at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotus-model-0.3.2/lib/lotus/model/config/adapter.rb:81
                     _build_adapter at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotus-model-0.3.2/lib/lotus/model/configuration.rb:168
                              load! at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotus-model-0.3.2/lib/lotus/model/configuration.rb:59
                              load! at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotus-model-0.3.2/lib/lotus/model.rb:87
                              <top> at /Users/serdardogruyol/playground/lotus-sample/lib/lotus-sample.rb:4
                            require at org/jruby/RubyKernel.java:941
                             (root) at uri:classloader:/jruby/kernel/kernel.rb:1
                              <top> at uri:classloader:/jruby/kernel/kernel.rb:24
                            require at org/jruby/RubyKernel.java:941
                    block in (root) at /Users/serdardogruyol/playground/lotus-sample/config/environment.rb:4
                      instance_eval at org/jruby/RubyBasicObject.java:1639
                             (root) at /Users/serdardogruyol/playground/lotus-sample/config.ru:1
                             <eval> at /Users/serdardogruyol/playground/lotus-sample/config.ru:1
                               eval at org/jruby/RubyKernel.java:980
                         initialize at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/builder.rb:55
                    new_from_string at /Users/serdardogruyol/playground/lotus-sample/config.ru:0
                    new_from_string at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/builder.rb:49
                         parse_file at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/builder.rb:40
  build_app_and_options_from_config at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/server.rb:299
                                app at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/server.rb:208
                        wrapped_app at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/server.rb:336
                              start at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/rack-1.6.1/lib/rack/server.rb:272
                              start at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotusrb-0.3.2/lib/lotus/commands/server.rb:47
                             server at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/lotusrb-0.3.2/lib/lotus/cli.rb:32
                                run at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/thor-0.19.1/lib/thor/command.rb:27
                     invoke_command at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/thor-0.19.1/lib/thor/invocation.rb:126
                              <top> at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/thor-0.19.1/lib/thor.rb:359
                               load at org/jruby/RubyKernel.java:959
                             <eval> at /Users/serdardogruyol/.rvm/gems/jruby-head/gems/thor-0.19.1/lib/thor/base.rb:440
                               eval at org/jruby/RubyKernel.java:980
                              <top> at /Users/serdardogruyol/.rvm/gems/jruby-head/bin/jruby_executable_hooks:15
```

**Comment by jodosha** [comment]
@Sdogruyol http://entrproject.org/

**Comment by joneslee85** [comment]
@Sdogruyol ping

**Comment by Sdogruyol** [comment]
@joneslee85 pong

**Comment by joneslee85** [comment]
@Sdogruyol any update?

**Comment by Ch4s3** [comment]
+1

**Comment by jodosha** [comment]
Closing in favor of #307
