### ISSUE TITLE
Error to use rack middleware with session dependency

### ISSUE THREAD

**Issue by vyper** [lotus/lotus#283]
If I use in `application.rb`:

```ruby
  sessions :cookie, secret: ENV['SESSIONS_SECRET']
  middleware.use OmniAuth::Builder do
    provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
  end
```

I received this error:

```
OmniAuth::NoSessionError: You must provide a session to use OmniAuth.

~/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:175:in `call!'
~/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
~/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
~/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
~/gems/lotusrb-0.4.0/lib/lotus/middleware.rb:53:in `call'
~/gems/lotusrb-0.4.0/lib/lotus/application.rb:217:in `call'
~/gems/http_router-0.11.1/lib/http_router.rb:193:in `process_destination_path'
(eval):15:in `call'
~/gems/http_router-0.11.1/lib/http_router.rb:288:in `raw_call'
~/gems/lotus-router-0.4.1/lib/lotus/routing/http_router.rb:179:in `raw_call'
~/gems/http_router-0.11.1/lib/http_router.rb:142:in `call'
~/gems/lotus-router-0.4.1/lib/lotus/router.rb:878:in `call'
~/gems/lotusrb-0.4.0/lib/lotus/container.rb:36:in `call'
~/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
~/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
~/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
~/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
~/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
~/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
~/gems/puma-2.11.3/lib/puma/rack_patch.rb:13:in `call'
~/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
~/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
~/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
~/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
~/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
~/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

But, when I use this code, work perfectly. 

```ruby
middleware.use Rack::Session::Cookie, secret: ENV['SESSIONS_SECRET']
middleware.use OmniAuth::Builder do
  provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
end
```

In `lotusrb-0.4.0/lib/lotus/middleware.rb:51`

```ruby
def call(env)
  # here, env['rack.session'] is nil for code:
  #   sessions sessions :cookie, secret: ENV['SESSIONS_SECRET'] 
  # and filled for code:
  #   middleware.use Rack::Session::Cookie, secret: ENV['SESSIONS_SECRET']
  @builder.call(env) 
end
```

**Comment by jodosha** [comment]
@vyper Thank you for reporting this. We're going to explore the code and try to make sessions shared with the middleware stack. :+1:

**Comment by vyper** [comment]
Cool! :+1:

**Comment by vyper** [comment]
@jodosha I test new version, but I got an errors...

# Using configuration

```ruby
sessions :cookie, secret: ENV['SESSIONS_SECRET']
middleware.use Rack::Session::Cookie, secret: ENV['SESSIONS_SECRET']
middleware.use OmniAuth::Builder do
  provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
end
```

# Specs ran perfectly
```
rspec spec/web/features/login_spec.rb
.......

Finished in 0.95783 seconds (files took 0.91043 seconds to load)
7 examples, 0 failures

# Or this version
rspec spec/web/features/
.......

Finished in 0.95783 seconds (files took 0.91043 seconds to load)
7 examples, 0 failures
```

# Using "lotus way" configuration

```ruby
sessions :cookie, secret: ENV['SESSIONS_SECRET']
middleware.use OmniAuth::Builder do
  provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
end
```

```
rspec spec/web/features/login_spec.rb
.......

Finished in 0.95783 seconds (files took 0.91043 seconds to load)
7 examples, 0 failures

# Or this version
rspec spec/web/features/
FFFFFFF

Finished in 1.52 seconds (files took 0.95663 seconds to load)
7 examples, 7 failures
```

**Comment by jackfranklin** [comment]
@jodosha I've just stumbled upon this same bug myself. In my `apps/web/application.rb` I have:

```rb
      sessions :cookie, secret: ENV['WEB_SESSIONS_SECRET']
      middleware.use OmniAuth::Builder do
        provider :twitter, ENV["TWITTER_KEY"], ENV["TWITTER_SECRET"]
      end
```

And running this in a browser works great, everything is good. I wrote a feature spec to cover this behaviour:

```rb
RSpec.describe 'Logging in from Twitter' do
  before do
    OmniAuth.config.add_mock(:twitter, uid: '1234', info: {
      nickname: 'Jack'
    })
  end

  it 'shows the user the welcome page' do
    visit '/auth/twitter'

    expect(page.body).to include('Welcome, Jack')
  end
end
```

And running:

```
rspec spec/web/features/logging_in_spec.rb
```

Passes just fine. However, as @vyper found, as soon as I give RSpec a folder path that includes > 1 spec, it errors:

```
Failures:

  1) Logging in from Twitter shows the user the welcome page
     Failure/Error: visit '/auth/twitter'
     OmniAuth::NoSessionError:
       You must provide a session to use OmniAuth.
     # ./.bundle/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:175:in `call!'
     # ./.bundle/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
     # ./.bundle/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
     # ./.bundle/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
     # ./.bundle/gems/lotusrb-0.4.1/lib/lotus/middleware.rb:52:in `call'
     # ./.bundle/gems/lotusrb-0.4.1/lib/lotus/application.rb:217:in `call'
     # ./.bundle/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
     # (eval):15:in `call'
     # ./.bundle/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
     # ./.bundle/gems/lotus-router-0.4.2/lib/lotus/routing/http_router.rb:123:in `raw_call'
     # ./.bundle/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
  ```

**Comment by vyper** [comment]
Thanks @jackfranklin for more details. (:
