### ISSUE TITLE
Irregular Routes not properly singularized in tests

### ISSUE THREAD

**Issue by davejlong** [lotus/lotus#340]
In my application, I have a set of resources called "children":

    resources :children, only: [:index, :show, :new]

In my index template, I use the route helper `routes.child_path(id: child.id)` in my list of children:

```
- if has_error?
  %div.alert-box.warning.radius(data-alert)= error_message

- if children.any?
  - children.each do |child|
    .child
      %a(href="#{routes.child_path(id: child.id)}")
        %h3= child.name
- else
  %div.alert-box.warning.radius(data-alert) There are no children available.
```

When I load up the page in the web browser, it works fine, but when I run my tests they fail that the route can't be generated. The tests pass if I change my code to `routes.children_path(id: child.id)`:

```
Randomized with seed 52101
......FF.......

Failures:

  1) Admin::Views::Children::Index when there are children hides the placeholder message
     Failure/Error: let(:rendered)  { view.render }
     Lotus::Routing::InvalidRouteException:
       No route (path) could be generated for :child
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-router-0.4.2/lib/lotus/routing/http_router.rb:157:in `rescue in _rescue_url_recognition'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-router-0.4.2/lib/lotus/routing/http_router.rb:154:in `_rescue_url_recognition'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-router-0.4.2/lib/lotus/routing/http_router.rb:79:in `raw_path'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-router-0.4.2/lib/lotus/router.rb:905:in `path'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotusrb-0.4.1/lib/lotus/routes.rb:74:in `path'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotusrb-0.4.1/lib/lotus/routes.rb:145:in `public_send'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotusrb-0.4.1/lib/lotus/routes.rb:145:in `method_missing'
     # apps/admin/templates/children/index.html.haml:7:in `block (2 levels) in singleton class'
     # apps/admin/templates/children/index.html.haml:5:in `each'
     # apps/admin/templates/children/index.html.haml:5:in `block in singleton class'
     # apps/admin/templates/children/index.html.haml:-9:in `instance_eval'
     # apps/admin/templates/children/index.html.haml:-9:in `singleton class'
     # apps/admin/templates/children/index.html.haml:-11:in `__tilt_70222875066880'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-view-0.4.3/lib/lotus/view/template.rb:39:in `render'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-view-0.4.3/lib/lotus/view/rendering.rb:117:in `rendered'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-view-0.4.3/lib/lotus/view/rendering.rb:131:in `layout'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-view-0.4.3/lib/lotus/view/rendering.rb:104:in `render'
     # ./spec/admin/views/children/index_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ./spec/admin/views/children/index_spec.rb:32:in `block (3 levels) in <top (required)>'

  2) Admin::Views::Children::Index when there are children lists them all
     Failure/Error: let(:rendered)  { view.render }
     Lotus::Routing::InvalidRouteException:
       No route (path) could be generated for :child
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-router-0.4.2/lib/lotus/routing/http_router.rb:157:in `rescue in _rescue_url_recognition'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-router-0.4.2/lib/lotus/routing/http_router.rb:154:in `_rescue_url_recognition'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-router-0.4.2/lib/lotus/routing/http_router.rb:79:in `raw_path'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-router-0.4.2/lib/lotus/router.rb:905:in `path'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotusrb-0.4.1/lib/lotus/routes.rb:74:in `path'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotusrb-0.4.1/lib/lotus/routes.rb:145:in `public_send'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotusrb-0.4.1/lib/lotus/routes.rb:145:in `method_missing'
     # apps/admin/templates/children/index.html.haml:7:in `block (2 levels) in singleton class'
     # apps/admin/templates/children/index.html.haml:5:in `each'
     # apps/admin/templates/children/index.html.haml:5:in `block in singleton class'
     # apps/admin/templates/children/index.html.haml:-9:in `instance_eval'
     # apps/admin/templates/children/index.html.haml:-9:in `singleton class'
     # apps/admin/templates/children/index.html.haml:-11:in `__tilt_70222875066880'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-view-0.4.3/lib/lotus/view/template.rb:39:in `render'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-view-0.4.3/lib/lotus/view/rendering.rb:117:in `rendered'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-view-0.4.3/lib/lotus/view/rendering.rb:131:in `layout'
     # /Users/davejlong/.rvm/gems/ruby-2.2.3/gems/lotus-view-0.4.3/lib/lotus/view/rendering.rb:104:in `render'
     # ./spec/admin/views/children/index_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ./spec/admin/views/children/index_spec.rb:26:in `block (3 levels) in <top (required)>'

Finished in 0.0505 seconds (files took 0.78828 seconds to load)
15 examples, 2 failures

Failed examples:

rspec ./spec/admin/views/children/index_spec.rb:31 # Admin::Views::Children::Index when there are children hides the placeholder message
rspec ./spec/admin/views/children/index_spec.rb:25 # Admin::Views::Children::Index when there are children lists them all

Randomized with seed 52101
```

The code for the application can be found at https://github.com/davejlong/coh

**Comment by jodosha** [comment]
@AlfonsoUceda Can you please fix this in Lotus::Router once you will come back from vacation? :palm_tree:

**Comment by jodosha** [comment]
> The tests pass if I change my code to routes.children_path(id: child.id)

@davejlong Can you please verify that in test mode the route `routes.children_path(id: child.id)` will generate `/children/1` and not `/children?id=1`.

Another helpful information is:

```shell
bundle exec lotus routes
```

and

```shell
LOTUS_ENV=test bundle exec lotus routes
```

Thank you! :+1:

**Comment by AlfonsoUceda** [comment]
Hi @davejlong after investigating, it isn't a bug, in your code you create a new instance of child because of this, the id is nil, then lotus router raise an exception.

If you provide in your tests the id, test passes.

```ruby
    let(:child1) { Child.new name: "Joshua Kisakye", id: 1 }
    let(:child2) { Child.new name: "Confiance Umurungezi", id: 2 }
```

**Comment by jodosha** [comment]
@AlfonsoUceda Excellent job :clap:

**Comment by davejlong** [comment]
Thank you @AlfonsoUceda. Still getting used to changing from the Rails ideologies to Lotus ideologies.
